lane :test do
  trello(
    api_key: "a1B2c3D4a1B2c3D4a1B2c3D4",
    api_token: "a1B2c3D4a1B2c3D4a1B2c3D4a1B2c3D4a1B2c3D4a1B2c3D4",
    board_id: "a1B2c3D4",
    list_name: "Done",
    card_number: 123
  )
end
